server:
  port: 9092
spring:
  application:
    name: biletx-gateway-service
  cloud:
    gateway:
      routes:
        - id: biletx-service
          uri: lb://biletx-service
          predicates:
            - Path=/users/**,/vehicles/**
        - id: biletx-payment-service
          uri: lb://biletx-payment-service
          predicates:
            - Path=/payments/**
       # - id: emlakcepte-payment-service
       #   uri: lb://emlakcepte-payment-service
        #  predicates:
         #   - Path=/payments/**

