server:
  port: 9092
spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: biletx-service
          uri: lb://biletx-service
          predicates:
            - Path=/users/**,/admins/**,/vehicles/**
        - id: emlakcepte-banner-service
          uri: lb://emlakcepte-banner-service
          predicates:
            - Path=/banners/**
        - id: emlakcepte-payment-service
          uri: lb://emlakcepte-payment-service
          predicates:
            - Path=/payments/**
